language: cpp

sudo: required
dist: trusty

before_script:
  - git fetch --unshallow
  - sudo apt-get install xsltproc
  - sudo apt-get install mtasc

script:
  - ./autogen.sh
  - ./configure
  - make distcheck
